#!/bin/bash

ZAPPROBDIR="/home/lindsayad/projects/zapdos/problems/"
INSTRING="mean_en"
ROOTSTRING=$INSTRING
OUTSTRING=$ROOTSTRING"_H_1e7_en_0"

cp $ZAPPROBDIR"log.txt" $ZAPPROBDIR"MooseLogs/log_"$OUTSTRING"_gold.txt"
cp $ZAPPROBDIR$INSTRING".i" $ZAPPROBDIR$OUTSTRING"_gold.i"
cp $ZAPPROBDIR$INSTRING"_out.e" $ZAPPROBDIR"MooseOutput/"$OUTSTRING"_gold_out.e"
cp $ZAPPROBDIR"liquidNew.geo" $ZAPPROBDIR$OUTSTRING"_gold.geo"

# cp $ZAPPROBDIR"log.txt" $ZAPPROBDIR"MooseLogs/log_"$OUTSTRING".txt"
# cp $ZAPPROBDIR$INSTRING".i" $ZAPPROBDIR$OUTSTRING".i"
# cp $ZAPPROBDIR$INSTRING"_out.e" $ZAPPROBDIR"MooseOutput/"$OUTSTRING"_out.e"
# cp $ZAPPROBDIR"liquidKinetic.msh" $ZAPPROBDIR"MooseMeshes/"$OUTSTRING".msh"
