#!/bin/bash

ZAPPROBDIR="/home/lindsayad/projects/zapdos/problems/"
INSTRING="DCPlasma_argon_energy_variable_trans_for_compare"
OUTSTRING=$INSTRING"_townsend_spline_var_iz_const_el_new_ip_trans_small_plasma_radius_lg_b_resist"

mv "log.txt" $ZAPPROBDIR"MooseLogs/log_"$OUTSTRING"_gold.txt"
cp $ZAPPROBDIR$INSTRING".i" $ZAPPROBDIR$OUTSTRING"_gold.i"
mv $ZAPPROBDIR$INSTRING"_out.e" $ZAPPROBDIR"MooseOutput/"$OUTSTRING"_gold_out.e" 

# mv "log.txt" $ZAPPROBDIR"MooseLogs/log_"$OUTSTRING".txt"
# cp $ZAPPROBDIR$INSTRING".i" $ZAPPROBDIR$OUTSTRING".i"
# mv $ZAPPROBDIR$INSTRING"_out.e" $ZAPPROBDIR"MooseOutput/"$OUTSTRING"_out.e" 

