#include "CraneApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template<>
InputParameters validParams<CraneApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  params.set<bool>("use_legacy_output_syntax") = false;

  return params;
}

CraneApp::CraneApp(InputParameters parameters) :
    MooseApp(parameters)
{
  Moose::registerObjects(_factory);
  CraneApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  CraneApp::associateSyntax(_syntax, _action_factory);
}

CraneApp::~CraneApp()
{
}

// External entry point for dynamic application loading
extern "C" void CraneApp__registerApps() { CraneApp::registerApps(); }
void
CraneApp::registerApps()
{
  registerApp(CraneApp);
}

// External entry point for dynamic object registration
extern "C" void CraneApp__registerObjects(Factory & factory) { CraneApp::registerObjects(factory); }
void
CraneApp::registerObjects(Factory & /*factory*/)
{
}

// External entry point for dynamic syntax association
extern "C" void CraneApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { CraneApp::associateSyntax(syntax, action_factory); }
void
CraneApp::associateSyntax(Syntax & /*syntax*/, ActionFactory & /*action_factory*/)
{
}
