#!/bin/bash

STRING=plasma_out.e

rm $STRING
COUNTER=0
MAX=212

until (( COUNTER == 10 || COUNTER == MAX )) ; do
        rm $STRING"-s00"$COUNTER 
	let COUNTER=COUNTER+1
done
until (( COUNTER == 100 || COUNTER == MAX )) ; do
        rm $STRING"-s0"$COUNTER 
	let COUNTER=COUNTER+1
done
until (( COUNTER == 1000 || COUNTER == MAX )) ; do
        rm $STRING"-s"$COUNTER
	let COUNTER=COUNTER+1
done


# while [ $COUNTER -lt $MAX ] ; do
#   while [ $COUNTER -lt 10 ] ; do
#        rm $STRING"-s00"$COUNTER 
#        let COUNTER=COUNTER+1
#   done
#   while [ $COUNTER -lt 100 ] ; do
#        rm $STRING"-s0"$COUNTER 
#        let COUNTER=COUNTER+1
#   done
#   while [ $COUNTER -lt 1000 ] ; do
#        rm $STRING"-s"$COUNTER
#        let COUNTER=COUNTER+1
#   done
#   # while [ $COUNTER -lt 1288 ] ; do
#   #      rm $STRING"-s"$COUNTER
#   #      let COUNTER=COUNTER+1
#   # done
# done
