#!/bin/bash

COUNTER=10
while [ $COUNTER -lt 99 ] ; do
     rm peacock_run_tmp_out.e-s0$COUNTER 
     let COUNTER=COUNTER+1
done
# while [ $COUNTER -lt 999 ] ; do
#      rm peacock_run_tmp_out.e-s$COUNTER
#      let COUNTER=COUNTER+1
# done
# while [ $COUNTER -lt 1288 ] ; do
#      rm peacock_run_tmp_out.e-s$COUNTER
#      let COUNTER=COUNTER+1
# done