#!/bin/bash

STRING=plasma_out.e-s

COUNTER=138
while [ $COUNTER -lt 99 ] ; do
     rm $STRING"0"$COUNTER 
     let COUNTER=COUNTER+1
done
while [ $COUNTER -lt 220 ] ; do
     rm $STRING$COUNTER
     let COUNTER=COUNTER+1
done
# while [ $COUNTER -lt 1288 ] ; do
#      rm $STRING$COUNTER
#      let COUNTER=COUNTER+1
# done